#+STARTUP:indent
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/styles.css"/>
#+HTML_HEAD_EXTRA: <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono|Ubuntu' rel='stylesheet' type='text/css'>
#+HTML_HEAD_EXTRA: <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
#+HTML_HEAD_EXTRA: <script src="js/navbar.js" type="text/javascript"></script>
#+OPTIONS: f:nil author:nil num:nil creator:nil timestamp:nil toc:nil html-style:nil

#+TITLE: ESafety
#+AUTHOR: Paul Dougall

#+BEGIN_HTML
  <div class="github-fork-ribbon-wrapper left">
    <div class="github-fork-ribbon">
      <a href="https://github.com/MarcScott/7-CS-ESafety">Fork me on GitHub</a>
    </div>
  </div>
<div id="stickyribbon">
    <ul>
      <li><a href="1_Lesson.html">Week1</a></li>
      <li><a href="2_Lesson.html">Week2</a></li>
      <li><a href="3_Lesson.html">Week3</a></li>
      <li><a href="assessment.html">Assessment</a></li>
    </ul>
  </div>
#+END_HTML
* COMMENT Use as a template
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:

** Research It
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:

** Design It
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:

** Build It
:PROPERTIES:
:HTML_CONTAINER_CLASS: build
:END:

** Test It
:PROPERTIES:
:HTML_CONTAINER_CLASS: test
:END:

** Run It
:PROPERTIES:
:HTML_CONTAINER_CLASS: run
:END:

** Document It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:

** Code It
:PROPERTIES:
:HTML_CONTAINER_CLASS: code
:END:

** Program It
:PROPERTIES:
:HTML_CONTAINER_CLASS: program
:END:

** Try It
:PROPERTIES:
:HTML_CONTAINER_CLASS: try
:END:

** Badge It
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:

** Save It
:PROPERTIES:
:HTML_CONTAINER_CLASS: save
:END:

* Grooming - What is it?
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:
- Grooming is when someone builds an emotional connection with a child to gain their trust for the purposes of abuse, exploitation or trafficking.
- Children and young people can be groomed online or face-to-face, by a stranger or by someone they know - for example a family member, friend or professional.
- Groomers may be male or female. They could be any age.
- Many children and young people don't understand that they have been groomed or that what has happened is abuse.
- 

** Watch It
:PROPERTIES:
:HTML_CONTAINER_CLASS: try
:END:

- Before we watch some videos below please answer the following questions:
- =Don't worry these are for you and are not submitted to anyone else.=

#+begin_html
 <form>
1. Do you currently use the internet?:<br>
<input type="radio" name="net" value="Yes" checked>Yes
<input type="radio" name="net" value="No">No<br><br>
If yes: home, school or both?<br><br>
<input type="text" name="home"></br>
<p>
2. How often to you use the internet?:<br>
<select name='times'>
<option value="Less than once a week"> Less than once a week <option>
<option value="Once a week"> Once a week <option>
<option value="2-3 times a week"> 2-3 times a week <option>
<option value="Almost everyday"> Almost everyday <option>
<option value="Everyday"> Everyday <option>
</select>
<p>
3. Do you use interactive internet applications such as:<br>
chatrooms<br>
<select name='options'>
<option value="Yes"> Yes <option>
<option value="No"> No <option>
<option value="Don't know"> Don't know <option>
</select> <br>
email</br>
<select name='options'>
<option value="No"> No <option>
<option value="Yes"> Yes <option>
<option value="Don't know"> Don't know <option>
</select>
<br>
Instant messaging</br>
<select name='options'>
<option value="Yes"> Yes <option>
<option value="No"> No <option>
<option value="Don't know"> Don't know <option>
</select>
<br>
<p>
4. If yes, do you save conversations that you have with people you meet online?</br>
<select name='options'>
<option value="No"> No <option>
<option value="Yes"> Yes <option>
<option value="Don't know"> Don't know <option>
</select> <br>
email</br>
<select name='options'>
<option value="Yes"> Yes <option>
<option value="No"> No <option>
<option value="Don't know"> Don't know <option>
</select>
<br>
Instant messaging</br>
<select name='options'>
<option value="No"> No <option>
<option value="Yes"> Yes <option>
<option value="Don't know"> Don't know <option>
</select>
<br>
<p>
5. Have you ever given out any personal details(like your name, address, phone number, a photo of yourself, your school name, school address) to someone you haven't met face to face
when using chatrooms or Instant Messaging?</br>
<input type="radio" name="out" value="Yes" checked>Yes
<br><input type="radio" name="out" value="No">No
<br><input type="radio" name="out" value="Don't know">Don't know<br><br>
If so, what details have you given?<br>
<textarea name="out" rows="1" cols="50">
</textarea> </br><br>

6. Have you ever threatened or made to feel uncomfortable by someone when using email, Instant Messenger, a chatroom, or your mobile phone? <br>
<input type="radio" name="yuk" value="Yes">Yes
<br><input type="radio" name="yuk" value="No" checked>No
<br><input type="radio" name="yuk" value="Don't know">Don't know<br>
<p>
7. If you felt threatened or bullied by someone who contacted you on the internet or on your mobile phone, who would you tell?<br>

<select name='people'>
<option value="No-one"> No one <option>
<option value="Friend"> Friend <option>
<option value="Parent"> Parent <option>
<option value="Teacher"> Teacher <option>
<option value="Police"> Police <option>
<option value="Childline"> Childline <option>
<option value="Other"> Other <option>
</select><br>

If other - whom?
<input type="text" name="person"> <br>

<p>
8. Has someone you've met on the internet contacted you by phone or post?<br>

<input type="radio" name="yuk" value="No">No
<br><input type="radio" name="yuk" value="Yes">Yes
<br><input type="radio" name="yuk" value="Don't know" checked>Don't know<br>
<p>
9. Have you ever asked or bene asked to meet up with somone face to face that you first met on the internet?<br>
<input type="radio" name="yuk" value="Yes">Yes
<br><input type="radio" name="yuk" value="No">No
<br><input type="radio" name="yuk" value="Don't know" checked>Don't know<br>
<p>
10. Who would you tell if you were meeting up with someone you met on the internet?<br>

<select name='people'>
<option value="No-one"> No one <option>
<option value="Friend"> Friend <option>
<option value="Parent"> Parent <option>
<option value="Teacher"> Teacher <option>
<option value="Police"> Police <option>
<option value="Childline"> Childline <option>
<option value="Other"> Other <option>
</select><br>

If other - whom?
<input type="text" name="person"> <br>No one etc..

<p>

11. Do you know how to block someone from contacting you on the Internet?<br>

<input type="radio" name="block" value="No">No <br>
<br><input type="radio" name="block" value="No">No<br>
<br><input type="radio" name="block" value="Don't know" checked>Don't know<br>
<p>

12. If you have the internet at home, do you: <br>
Have filtering software? <br>
<select name='options'>
<option value="Yes"> Yes <option>
<option value="No"> No <option>
<option value="Don't know"> Don't know <option>
</select> <br>
Use it in front of an adult? <br>
<select name='options'>
<option value="No"> No <option>
<option value="Yes"> Yes <option>
<option value="Don't know"> Don't know <option>
</select> <br>
Know that an adult check the history?<br>
<select name='options'>
<option value="Yes"> Yes <option>
<option value="No"> No <option>
<option value="Don't know"> Don't know <option>
</select> <br>
Talk to an adult about what you have been doing? <br>
<select name='options'>
<option value="No"> No <option>
<option value="Yes"> Yes <option>
<option value="Don't know"> Don't know <option>
</select> <br>
<p>

</form>
#+end_html
* Grooming - How does it happen?
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
- Grooming happens both online and in person. 
- Groomers will hide their true intentions and may spend a long time gaining a child's trust. 
- Groomers may try to gain the trust of a whole family to allow them to be left alone with a child and if they work with children they may use similar tactics with their colleagues.
  Groomers do this by:

- pretending to be someone they are not, for example saying they are the same age online
- offering advice or understanding
- buying gifts, alcohol, drugs
- giving the child attention
- using their professional position or reputation
- taking them on trips, outings or holidays.



#+BEGIN_HTML
<iframe width="800" height="400" src="https://www.youtube.com/embed/Z5WEnqnq1Hk" frameborder="0" allowfullscreen></iframe>
#+END_HTML

- This is not just an issue that affects girls. Boys can groomed online as well.

#+BEGIN_HTML
<iframe width="800" height="400" src="https://www.youtube.com/embed/9JpyO5XlfCo" frameborder="0" allowfullscreen></iframe>
#+END_HTML

* End this
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:

